@startuml project-sensor
'https://plantuml.com/component-diagram

title Project Sensor SW Architecture

node "Project Sensor" {
    frame "Control" {
        package "Managment App" {
            package "Init" {
              [run.sh]
            }
            package "Back End" {
              [Event-Driven Core]
              [Model]
            }
            package "Controllers" {
              [tcp-controller.js]
              [http-controller.js]
              [uart-controller.js]
            }
            "Controllers" --> "Back End" : control
        }
    }

    frame "Video" {
        frame "Cameras" {
            [Camera1]
            [Camera2]
            [Camera3]
            [Camera4]
        }

        package "media-server" {
            [MediaMTX]
        }

        package "video" {
            [GStreamer Pipeline]
        }

        package "video-processing" {
            frame "preprocessing" {
                [Gstreamer Plugin 1]
            }

            frame "postprocessing" {
                [Gstreamer Plugin 2]
            }
        }
    }

    package "Web" {
        frame "web-server" {
            [Nginx]
        }
        frame "Front End (View)" {
            [index.html]
        }
    }

}

node "User PC" {
    package "Web Browser" {
        frame "Project Sensor Web Portal" {
            [Camera Stream 1]
            [Camera Stream 2]
            [Camera Stream 3]
            [Camera Stream 4]
        }
    }
    package "Media Client" {
        [RTSP Camera Stream 1]
        [RTSP Camera Stream 2]
        [RTSP Camera Stream 3]
        [RTSP Camera Stream 4]
    }
}

"Project Sensor Web Portal" <--> "Front End (View)"
"web-server" --> "Controllers"
"Front End (View)" --> "web-server"
"Back End" --> "video" : control
"media-server" --> "Front End (View)" : stream
"media-server" --> "Media Client" : stream
"video" --> "Cameras" : control
"video" --> "video-processing"  : control
"video" --> "media-server" : stream
"Managment App" --> "media-server" : control
"Managment App" --> "web-server" : control

@enduml